spring:
  application:
    name: LakesideHotel

  datasource:
    url: jdbc:mysql://localhost:3307/lakeside_hotel_db
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082
